Product.create!([
  {title: "Hammers", price: "20.0", image_url: "blahhh", description: "It's a hammer", part_number: nil, inventory: nil},
  {title: "Test", price: "15.0", image_url: "blank", description: "fake description", part_number: nil, inventory: nil},
  {title: "Test", price: "15.0", image_url: "blank", description: "fake description", part_number: nil, inventory: nil},
  {title: "Magnemite", price: "94.0", image_url: "blank", description: "Holy Triple Feature", part_number: nil, inventory: nil},
  {title: "Voltorb", price: "72.0", image_url: "blank", description: "Holy Graf Zeppelin", part_number: nil, inventory: nil},
  {title: "Weedle", price: "94.0", image_url: "blank", description: "Holy Hallelujah", part_number: nil, inventory: nil},
  {title: "Nidoking", price: "15.0", image_url: "blank", description: "Holy Cinemascope", part_number: nil, inventory: nil},
  {title: "Beedrill", price: "51.0", image_url: "blank", description: "Holy Hunting Horn", part_number: nil, inventory: nil},
  {title: "Pikachu", price: "36.0", image_url: "blank", description: "Holy Horseshoes", part_number: nil, inventory: nil},
  {title: "Tentacruel", price: "23.0", image_url: "blank", description: "Holy Voltage", part_number: nil, inventory: nil},
  {title: "Bellsprout", price: "18.0", image_url: "blank", description: "Holy Haziness", part_number: nil, inventory: nil},
  {title: "Rhydon", price: "54.0", image_url: "blank", description: "Holy Bank Balance", part_number: nil, inventory: nil},
  {title: "Gyarados", price: "41.0", image_url: "blank", description: "Holy Key Hole", part_number: nil, inventory: nil},
  {title: "Exeggutor", price: "34.0", image_url: "blank", description: "Holy Tartars", part_number: nil, inventory: nil},
  {title: "Drowzee", price: "73.0", image_url: "blank", description: "Holy Titanic", part_number: nil, inventory: nil},
  {title: "Voltorb", price: "90.0", image_url: "blank", description: "Holy Razors Edge", part_number: nil, inventory: nil},
  {title: "Geodude", price: "40.0", image_url: "blank", description: "Holy Oxygen", part_number: nil, inventory: nil},
  {title: "Poliwag", price: "44.0", image_url: "blank", description: "Holy Hairdo", part_number: nil, inventory: nil},
  {title: "Pidgey", price: "27.0", image_url: "blank", description: "Holy Costume Party", part_number: nil, inventory: nil},
  {title: "Dodrio", price: "62.0", image_url: "blank", description: "Holy Wayne Manor", part_number: nil, inventory: nil},
  {title: "Onix", price: "36.0", image_url: "blank", description: "Holy Tome", part_number: nil, inventory: nil},
  {title: "Arcanine", price: "10.0", image_url: "blank", description: "Holy Epigrams", part_number: nil, inventory: nil},
  {title: "Aerodactyl", price: "16.0", image_url: "blank", description: "Holy Transistors", part_number: nil, inventory: nil},
  {title: "Golbat", price: "57.0", image_url: "blank", description: "Holy Hutzpa", part_number: nil, inventory: nil},
  {title: "Haunter", price: "30.0", image_url: "blank", description: "Holy Known Unknown Flying Objects", part_number: nil, inventory: nil},
  {title: "Seadra", price: "15.0", image_url: "blank", description: "Holy Hors D'Oeuvre", part_number: nil, inventory: nil},
  {title: "Wartortle", price: "94.0", image_url: "blank", description: "Holy Jaw Breaker", part_number: nil, inventory: nil},
  {title: "Bellsprout", price: "90.0", image_url: "blank", description: "Holy Hallucination", part_number: nil, inventory: nil},
  {title: "Gloom", price: "75.0", image_url: "blank", description: "Holy Smoke", part_number: nil, inventory: nil},
  {title: "Pidgeot", price: "84.0", image_url: "blank", description: "Holy Tipoffs", part_number: nil, inventory: nil},
  {title: "Weezing", price: "74.0", image_url: "blank", description: "Holy Homework", part_number: nil, inventory: nil},
  {title: "Vulpix", price: "74.0", image_url: "blank", description: "Holy Fruit Salad", part_number: nil, inventory: nil},
  {title: "Seel", price: "52.0", image_url: "blank", description: "Holy Bunions", part_number: nil, inventory: nil},
  {title: "Nidorina", price: "81.0", image_url: "blank", description: "Holy Trampoline", part_number: nil, inventory: nil},
  {title: "Staryu", price: "22.0", image_url: "blank", description: "Holy Catastrophe", part_number: nil, inventory: nil},
  {title: "Blastoise", price: "23.0", image_url: "blank", description: "Holy Ice Skates", part_number: nil, inventory: nil},
  {title: "Oddish", price: "64.0", image_url: "blank", description: "Holy Roadblocks", part_number: nil, inventory: nil},
  {title: "Wartortle", price: "29.0", image_url: "blank", description: "Holy History", part_number: nil, inventory: nil},
  {title: "Magnemite", price: "67.0", image_url: "blank", description: "Holy Anagram", part_number: nil, inventory: nil},
  {title: "Moltres", price: "16.0", image_url: "blank", description: "Holy Oleo", part_number: nil, inventory: nil},
  {title: "Mr. Mime", price: "87.0", image_url: "blank", description: "Holy History", part_number: nil, inventory: nil},
  {title: "Hitmonlee", price: "73.0", image_url: "blank", description: "Holy Nightmare", part_number: nil, inventory: nil},
  {title: "Clefairy", price: "64.0", image_url: "blank", description: "Holy Miscast", part_number: nil, inventory: nil},
  {title: "Gengar", price: "60.0", image_url: "blank", description: "Holy Pseudonym", part_number: nil, inventory: nil},
  {title: "Primeape", price: "70.0", image_url: "blank", description: "Holy Lodestone", part_number: nil, inventory: nil},
  {title: "Aerodactyl", price: "65.0", image_url: "blank", description: "Holy Ball And Chain", part_number: nil, inventory: nil},
  {title: "Muk", price: "93.0", image_url: "blank", description: "Holy Holocaust", part_number: nil, inventory: nil},
  {title: "Oddish", price: "54.0", image_url: "blank", description: "Holy Chocolate Eclair", part_number: nil, inventory: nil},
  {title: "Lickitung", price: "93.0", image_url: "blank", description: "Holy Ghost Writer", part_number: nil, inventory: nil},
  {title: "Goldeen", price: "87.0", image_url: "blank", description: "Holy Kilowatts", part_number: nil, inventory: nil},
  {title: "Cubone", price: "63.0", image_url: "blank", description: "Holy Looking Glass", part_number: nil, inventory: nil},
  {title: "Farfetch'd", price: "21.0", image_url: "blank", description: "Holy Oxygen", part_number: nil, inventory: nil},
  {title: "Kingler", price: "10.0", image_url: "blank", description: "Holy Homework", part_number: nil, inventory: nil},
  {title: "Marowak", price: "80.0", image_url: "blank", description: "Holy Ice Skates", part_number: nil, inventory: nil},
  {title: "Snorlax", price: "79.0", image_url: "blank", description: "Holy Taxidermy", part_number: nil, inventory: nil},
  {title: "Tentacruel", price: "45.0", image_url: "blank", description: "Holy Iceberg", part_number: nil, inventory: nil},
  {title: "Shellder", price: "22.0", image_url: "blank", description: "Holy Polar Front", part_number: nil, inventory: nil},
  {title: "Rhydon", price: "96.0", image_url: "blank", description: "Holy Pseudonym", part_number: nil, inventory: nil},
  {title: "Nidoran", price: "90.0", image_url: "blank", description: "Holy Journey To The Center Of The Earth", part_number: nil, inventory: nil},
  {title: "Machop", price: "51.0", image_url: "blank", description: "Holy Sardine", part_number: nil, inventory: nil},
  {title: "Golbat", price: "89.0", image_url: "blank", description: "Holy Cliche", part_number: nil, inventory: nil},
  {title: "Mew", price: "38.0", image_url: "blank", description: "Holy Key Hole", part_number: nil, inventory: nil},
  {title: "Clefairy", price: "94.0", image_url: "blank", description: "Holy Mechanical Armies", part_number: nil, inventory: nil},
  {title: "Jynx", price: "94.0", image_url: "blank", description: "Holy Transistors", part_number: nil, inventory: nil},
  {title: "Ditto", price: "28.0", image_url: "blank", description: "Holy Slipped Disc", part_number: nil, inventory: nil},
  {title: "Hitmonchan", price: "48.0", image_url: "blank", description: "Holy Shucks", part_number: nil, inventory: nil},
  {title: "Rhyhorn", price: "76.0", image_url: "blank", description: "Holy Split Seconds", part_number: nil, inventory: nil},
  {title: "Articuno", price: "40.0", image_url: "blank", description: "Holy Long John Silver", part_number: nil, inventory: nil},
  {title: "Omanyte", price: "40.0", image_url: "blank", description: "Holy Semantics", part_number: nil, inventory: nil},
  {title: "Zapdos", price: "90.0", image_url: "blank", description: "Holy Human Pearls", part_number: nil, inventory: nil},
  {title: "Koffing", price: "74.0", image_url: "blank", description: "Holy Mechanical Armies", part_number: nil, inventory: nil},
  {title: "Metapod", price: "40.0", image_url: "blank", description: "Holy Greed", part_number: nil, inventory: nil},
  {title: "Grimer", price: "69.0", image_url: "blank", description: "Holy Matador", part_number: nil, inventory: nil},
  {title: "Zubat", price: "40.0", image_url: "blank", description: "Holy Tee Shot", part_number: nil, inventory: nil},
  {title: "Gastly", price: "81.0", image_url: "blank", description: "Holy Roadblocks", part_number: nil, inventory: nil},
  {title: "Pikachu", price: "37.0", image_url: "blank", description: "Holy Armadillo", part_number: nil, inventory: nil},
  {title: "Meowth", price: "68.0", image_url: "blank", description: "Holy Sherlock Holmes", part_number: nil, inventory: nil},
  {title: "Cubone", price: "11.0", image_url: "blank", description: "Holy Hieroglyphic", part_number: nil, inventory: nil},
  {title: "Weezing", price: "97.0", image_url: "blank", description: "Holy Sundials", part_number: nil, inventory: nil},
  {title: "Dodrio", price: "25.0", image_url: "blank", description: "Holy Ricochet", part_number: nil, inventory: nil},
  {title: "Tentacool", price: "81.0", image_url: "blank", description: "Holy Cinderella", part_number: nil, inventory: nil},
  {title: "Poliwrath", price: "38.0", image_url: "blank", description: "Holy IT and T", part_number: nil, inventory: nil},
  {title: "Snorlax", price: "24.0", image_url: "blank", description: "Holy Black Beard", part_number: nil, inventory: nil},
  {title: "Arcanine", price: "60.0", image_url: "blank", description: "Holy Razors Edge", part_number: nil, inventory: nil},
  {title: "Gastly", price: "91.0", image_url: "blank", description: "Holy Trickery", part_number: nil, inventory: nil},
  {title: "Machop", price: "73.0", image_url: "blank", description: "Holy Paderewski", part_number: nil, inventory: nil},
  {title: "Dodrio", price: "14.0", image_url: "blank", description: "Holy Snowball", part_number: nil, inventory: nil},
  {title: "Electabuzz", price: "47.0", image_url: "blank", description: "Holy Giveaways", part_number: nil, inventory: nil},
  {title: "Bellsprout", price: "90.0", image_url: "blank", description: "Holy Knit One Purl Two", part_number: nil, inventory: nil},
  {title: "Seel", price: "91.0", image_url: "blank", description: "Holy Alter Ego", part_number: nil, inventory: nil},
  {title: "Raichu", price: "19.0", image_url: "blank", description: "Holy Sedatives", part_number: nil, inventory: nil},
  {title: "Metapod", price: "58.0", image_url: "blank", description: "Holy Ice Picks", part_number: nil, inventory: nil},
  {title: "Caterpie", price: "54.0", image_url: "blank", description: "Holy Astringent Plum-like Fruit", part_number: nil, inventory: nil},
  {title: "Rhydon", price: "63.0", image_url: "blank", description: "Holy Catastrophe", part_number: nil, inventory: nil},
  {title: "Farfetch'd", price: "46.0", image_url: "blank", description: "Holy Vat", part_number: nil, inventory: nil},
  {title: "Raticate", price: "24.0", image_url: "blank", description: "Holy Bat Logic", part_number: nil, inventory: nil},
  {title: "Ninetales", price: "82.0", image_url: "blank", description: "Holy Recompense", part_number: nil, inventory: nil},
  {title: "Slowbro", price: "53.0", image_url: "blank", description: "Holy Complications", part_number: nil, inventory: nil},
  {title: "Kadabra", price: "56.0", image_url: "blank", description: "Holy Steam Valve", part_number: nil, inventory: nil},
  {title: "Growlithe", price: "39.0", image_url: "blank", description: "Holy Hijack", part_number: nil, inventory: nil},
  {title: "Nidoran", price: "52.0", image_url: "blank", description: "Holy Rocking Chair", part_number: nil, inventory: nil},
  {title: "Magneton", price: "15.0", image_url: "blank", description: "Holy Gemini", part_number: nil, inventory: nil},
  {title: "Golduck", price: "83.0", image_url: "blank", description: "Holy Lodestone", part_number: nil, inventory: nil},
  {title: "TestProduct2", price: "14.0", image_url: "placeholder", description: "Testing testing 1, 2, 3.", part_number: nil, inventory: nil},
  {title: "TestProduct2", price: "14.0", image_url: "placeholder", description: "Testing testing 1, 2, 3.", part_number: nil, inventory: nil}
])
